# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import data_pb2 as data__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='rpc.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\trpc.proto\x1a\ndata.proto2 \n\x03RPC\x12\x19\n\x03run\x12\x08.ReqData\x1a\x08.ResData')
  ,
  dependencies=[data__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_RPC = _descriptor.ServiceDescriptor(
  name='RPC',
  full_name='RPC',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=25,
  serialized_end=57,
  methods=[
  _descriptor.MethodDescriptor(
    name='run',
    full_name='RPC.run',
    index=0,
    containing_service=None,
    input_type=data__pb2._REQDATA,
    output_type=data__pb2._RESDATA,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_RPC)

DESCRIPTOR.services_by_name['RPC'] = _RPC

# @@protoc_insertion_point(module_scope)
